version: "3.9"

services:
  app:
    build: .
    container_name: cod-login-app
    volumes:
      - .:/www/app
      - ./node_modules:/www/app/node_modules
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - cod-login-net

networks:
  cod-login-net:
    driver: bridge