import type { NextPage } from 'next'
import Head from 'next/head'
import Link from "next/link"
import { useRouter } from "next/router";
import styles from '@/presentation/styles/pages/Home.module.scss';
import { useEffect } from "react";

const Home: NextPage = () => {
    const { push } = useRouter()

    useEffect(() => {
        push("/login").then()
    }, [ push ])

    return (
        <div className={ styles.container }>
            <Head>
                <title>Inicio</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={ styles.main }>
                <h1 className={ styles.title }>
                    Bem vindo ao <Link href="/login">Code craft Club</Link>
                </h1>

                <p className={ styles.description }>
                    Se você não for redirecionado dentro de alguns segundos. <Link href={ '/login' }>Clique aqui</Link>
                </p>

            </main>


        </div>
    )
}

export default Home
